#!/usr/bin/env python3
"""Rebuild _global_index.md and each creator's _index.md from summary frontmatter.

Reads every <creator>/<id>.summary.md and aggregates by topic. Hand edits to
the index files are overwritten.
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib.paths import GLOBAL_INDEX, KNOWLEDGE_DIR, SOURCES_DIR, creator_index, creator_meta

_FM = re.compile(r"^---\n(.*?)\n---", re.DOTALL)


def parse_frontmatter(text: str) -> dict:
    m = _FM.match(text)
    if not m:
        return {}
    out: dict = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        k = k.strip()
        v = v.strip()
        if v.startswith("[") and v.endswith("]"):
            inner = v[1:-1].strip()
            out[k] = [x.strip().strip("'\"") for x in inner.split(",") if x.strip()] if inner else []
        elif v.startswith('"') and v.endswith('"'):
            out[k] = v[1:-1]
        else:
            out[k] = v
    return out


def collect() -> list[dict]:
    rows: list[dict] = []
    if not SOURCES_DIR.exists():
        return rows
    for creator_dir in sorted(SOURCES_DIR.iterdir()):
        if not creator_dir.is_dir():
            continue
        slug = creator_dir.name
        for summary in sorted(creator_dir.glob("*.summary.md")):
            fm = parse_frontmatter(summary.read_text(encoding="utf-8"))
            fm["_creator_slug"] = slug
            fm["_summary_path"] = str(summary.relative_to(KNOWLEDGE_DIR))
            transcript = summary.with_name(summary.name.replace(".summary.md", ".transcript.md"))
            fm["_transcript_path"] = str(transcript.relative_to(KNOWLEDGE_DIR)) if transcript.exists() else ""
            rows.append(fm)
    return rows


def write_creator_index(slug: str, rows: list[dict]) -> None:
    meta_path = creator_meta(slug)
    meta = {}
    if meta_path.exists():
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
        except Exception:
            meta = {}
    name = meta.get("name", slug)
    lines = [f"# {name} — videos in the brain", ""]
    if not rows:
        lines.append("_No videos yet. Use `add_video.py <URL>` then write a summary._")
    else:
        rows_sorted = sorted(rows, key=lambda r: r.get("upload_date", ""), reverse=True)
        lines.append("| Date | Title | Topics | Files |")
        lines.append("|---|---|---|---|")
        for r in rows_sorted:
            title = (r.get("title") or "").replace("|", "\\|")
            url = r.get("url", "")
            topics = ", ".join(r.get("topics", []) or [])
            files = f"[summary]({Path(r['_summary_path']).name})"
            if r.get("_transcript_path"):
                files += f" · [transcript]({Path(r['_transcript_path']).name})"
            lines.append(f"| {r.get('upload_date', '?')} | [{title}]({url}) | {topics} | {files} |")
    creator_index(slug).write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_global_index(rows: list[dict]) -> None:
    by_topic: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        for t in r.get("topics", []) or ["(untagged)"]:
            by_topic[t].append(r)

    lines = [
        "# Marketing Brain — Global Index",
        "",
        "_Auto-generated by `reindex.py`. Do not hand-edit. Read this first to decide which summaries to load when answering._",
        "",
        f"**Total videos:** {len(rows)} · **Creators:** {len({r['_creator_slug'] for r in rows})}",
        "",
        "## By topic",
        "",
    ]
    if not by_topic:
        lines.append("_Brain is empty._")
    else:
        for topic in sorted(by_topic.keys()):
            lines.append(f"### {topic}")
            lines.append("")
            for r in sorted(by_topic[topic], key=lambda r: r.get("upload_date", ""), reverse=True):
                title = r.get("title", "(no title)")
                url = r.get("url", "")
                summ = r["_summary_path"]
                lines.append(f"- [{title}]({url}) — {r.get('upload_date', '?')} · {r['_creator_slug']} · `{summ}`")
            lines.append("")

    lines.append("## By creator")
    lines.append("")
    by_creator: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_creator[r["_creator_slug"]].append(r)
    for slug in sorted(by_creator):
        lines.append(f"- **{slug}** — {len(by_creator[slug])} videos · `sources/{slug}/_index.md`")
    lines.append("")
    GLOBAL_INDEX.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    rows = collect()
    by_creator: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_creator[r["_creator_slug"]].append(r)
    for slug, slug_rows in by_creator.items():
        write_creator_index(slug, slug_rows)
    # Also write empty creator indexes (no summaries yet)
    if SOURCES_DIR.exists():
        for d in SOURCES_DIR.iterdir():
            if d.is_dir() and d.name not in by_creator:
                write_creator_index(d.name, [])
    write_global_index(rows)
    print(f"Reindexed {len(rows)} videos across {len(by_creator)} creators")
    print(f"Global index: {GLOBAL_INDEX}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
